# -*- coding: utf-8 -*-
from django.urls import path
from django.views.generic import TemplateView

from . import views


app_name = 'dj_beneficiary'
urlpatterns = [
    path(
        "individualbeneficiary/create/",
        view=views.IndividualBeneficiaryCreateView.as_view(),
        name='IndividualBeneficiary_create',
    ),
    path(
        "individualbeneficiary/(<int:pk>/delete/",
        view=views.IndividualBeneficiaryDeleteView.as_view(),
        name='IndividualBeneficiary_delete',
    ),
    path(
        "individualbeneficiary/<int:pk>/",
        view=views.IndividualBeneficiaryDetailView.as_view(),
        name='individual_eneficiary_detail',
    ),
    path(
        "individualbeneficiary/<int:pk>/update/",
        view=views.IndividualBeneficiaryUpdateView.as_view(),
        name='individual_eneficiary_update',
    ),
    path(
        "individualbeneficiary/",
        view=views.IndividualBeneficiaryListView.as_view(),
        name='individualbeneficiary_list',
    ),
	path(
        "Facility/create/",
        view=views.FacilityCreateView.as_view(),
        name='Facility_create',
    ),
    path(
        "Facility/<int:pk>/delete/",
        view=views.FacilityDeleteView.as_view(),
        name='Facility_delete',
    ),
    path(
        "Facility/<int:pk>/",
        view=views.FacilityDetailView.as_view(),
        name='Facility_detail',
    ),
    path(
        "Facility/<int:pk>/update/",
        view=views.FacilityUpdateView.as_view(),
        name='Facility_update',
    ),
    path(
        "Facility/",
        view=views.FacilityListView.as_view(),
        name='Facility_list',
    ),
	path(
        "Province/create/",
        view=views.ProvinceCreateView.as_view(),
        name='Province_create',
    ),
    path(
        "Province/<int:pk>/delete/",
        view=views.ProvinceDeleteView.as_view(),
        name='Province_delete',
    ),
    path(
        "Province/<int:pk>/",
        view=views.ProvinceDetailView.as_view(),
        name='Province_detail',
    ),
    path(
        "Province/<int:pk>/update/",
        view=views.ProvinceUpdateView.as_view(),
        name='Province_update',
    ),
    path(
        "Province/",
        view=views.ProvinceListView.as_view(),
        name='Province_list',
    ),
	path(
        "District/create/",
        view=views.DistrictCreateView.as_view(),
        name='District_create',
    ),
    path(
        "District/<int:pk>/delete/",
        view=views.DistrictDeleteView.as_view(),
        name='District_delete',
    ),
    path(
        "District/<int:pk>/",
        view=views.DistrictDetailView.as_view(),
        name='District_detail',
    ),
    path(
        "District/<int:pk>/update/",
        view=views.DistrictUpdateView.as_view(),
        name='District_update',
    ),
    path(
        "District/",
        view=views.DistrictListView.as_view(),
        name='District_list',
    ),
	path(
        "Ward/create/",
        view=views.WardCreateView.as_view(),
        name='Ward_create',
    ),
    path(
        "Ward/<int:pk>/delete/",
        view=views.WardDeleteView.as_view(),
        name='Ward_delete',
    ),
    path(
        "Ward/<int:pk>/",
        view=views.WardDetailView.as_view(),
        name='Ward_detail',
    ),
    path(
        "Ward/<int:pk>/update/",
        view=views.WardUpdateView.as_view(),
        name='Ward_update',
    ),
    path(
        "Ward/",
        view=views.WardListView.as_view(),
        name='Ward_list',
    ),
	]
