# -*- coding: utf-8 -*-
from django.conf.urls import url
from django.views.generic import TemplateView

from . import views


app_name = 'dj_beneficiary'
urlpatterns = [
    url(
        regex="^Beneficiary/~create/$",
        view=views.BeneficiaryCreateView.as_view(),
        name='Beneficiary_create',
    ),
    url(
        regex="^Beneficiary/(?P<pk>\d+)/~delete/$",
        view=views.BeneficiaryDeleteView.as_view(),
        name='Beneficiary_delete',
    ),
    url(
        regex="^Beneficiary/(?P<pk>\d+)/$",
        view=views.BeneficiaryDetailView.as_view(),
        name='Beneficiary_detail',
    ),
    url(
        regex="^Beneficiary/(?P<pk>\d+)/~update/$",
        view=views.BeneficiaryUpdateView.as_view(),
        name='Beneficiary_update',
    ),
    url(
        regex="^Beneficiary/$",
        view=views.BeneficiaryListView.as_view(),
        name='Beneficiary_list',
    ),
	url(
        regex="^Facility/~create/$",
        view=views.FacilityCreateView.as_view(),
        name='Facility_create',
    ),
    url(
        regex="^Facility/(?P<pk>\d+)/~delete/$",
        view=views.FacilityDeleteView.as_view(),
        name='Facility_delete',
    ),
    url(
        regex="^Facility/(?P<pk>\d+)/$",
        view=views.FacilityDetailView.as_view(),
        name='Facility_detail',
    ),
    url(
        regex="^Facility/(?P<pk>\d+)/~update/$",
        view=views.FacilityUpdateView.as_view(),
        name='Facility_update',
    ),
    url(
        regex="^Facility/$",
        view=views.FacilityListView.as_view(),
        name='Facility_list',
    ),
	url(
        regex="^Province/~create/$",
        view=views.ProvinceCreateView.as_view(),
        name='Province_create',
    ),
    url(
        regex="^Province/(?P<pk>\d+)/~delete/$",
        view=views.ProvinceDeleteView.as_view(),
        name='Province_delete',
    ),
    url(
        regex="^Province/(?P<pk>\d+)/$",
        view=views.ProvinceDetailView.as_view(),
        name='Province_detail',
    ),
    url(
        regex="^Province/(?P<pk>\d+)/~update/$",
        view=views.ProvinceUpdateView.as_view(),
        name='Province_update',
    ),
    url(
        regex="^Province/$",
        view=views.ProvinceListView.as_view(),
        name='Province_list',
    ),
	url(
        regex="^District/~create/$",
        view=views.DistrictCreateView.as_view(),
        name='District_create',
    ),
    url(
        regex="^District/(?P<pk>\d+)/~delete/$",
        view=views.DistrictDeleteView.as_view(),
        name='District_delete',
    ),
    url(
        regex="^District/(?P<pk>\d+)/$",
        view=views.DistrictDetailView.as_view(),
        name='District_detail',
    ),
    url(
        regex="^District/(?P<pk>\d+)/~update/$",
        view=views.DistrictUpdateView.as_view(),
        name='District_update',
    ),
    url(
        regex="^District/$",
        view=views.DistrictListView.as_view(),
        name='District_list',
    ),
	url(
        regex="^Ward/~create/$",
        view=views.WardCreateView.as_view(),
        name='Ward_create',
    ),
    url(
        regex="^Ward/(?P<pk>\d+)/~delete/$",
        view=views.WardDeleteView.as_view(),
        name='Ward_delete',
    ),
    url(
        regex="^Ward/(?P<pk>\d+)/$",
        view=views.WardDetailView.as_view(),
        name='Ward_detail',
    ),
    url(
        regex="^Ward/(?P<pk>\d+)/~update/$",
        view=views.WardUpdateView.as_view(),
        name='Ward_update',
    ),
    url(
        regex="^Ward/$",
        view=views.WardListView.as_view(),
        name='Ward_list',
    ),
	]
