# Generated by Django 4.0 on 2021-12-29 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FacilityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Facility Type Name')),
            ],
        ),
        migrations.CreateModel(
            name='ImplementingPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('ip_type', models.IntegerField(choices=[(1, 'Non-Profit Organization'), (2, 'Company'), (3, 'Government'), (4, 'Other')], default=1, verbose_name='Type')),
                ('is_active', models.BooleanField(default=True, help_text='Is still an active Implementing Partner', verbose_name='Is Active')),
            ],
        ),
    ]
