# Generated by Django 4.0 on 2021-12-29 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dj_beneficiary', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrganizationBeneficiary',
        ),
    ]
