# Generated by Django 4.0.4 on 2022-04-11 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_utils', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beneficiary',
            options={'verbose_name': 'Beneficiary Organization', 'verbose_name_plural': 'Beneficiary Organizations'},
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Organization Name'),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='org_type',
            field=models.CharField(blank=True, choices=[('coorperative', 'Co-orperative'), ('businessfirm', 'Business Firm'), ('Other', 'Other')], max_length=100, null=True, verbose_name='Organization Type'),
        ),
    ]
